### ISSUE TITLE
Prevenire operazione se uno dei due campi input è vuoto

### ISSUE THREAD

**Issue by matteobarone** [matteobarone/calculator#3]
@manuelalonge lo vediamo domani

**Comment by manuelalonge** [comment]
`function calculateTotal(value1, value2) {
        if (value1 === '' || value2 === '') {
            return 'Not applicable';
        };
    
        const n1 = parseInt(value1);
        const n2 = parseInt(value2);
    
        return getOperation(n1, n2);
    };`

**Comment by ghost** [comment]
@matteobarone dovrebbe essere questo pezzo di codice a fare l'operazione che mi dici, giusto?

```
function calculateTotal(value1, value2) {
        if (value1 === '' || value2 === '') {
            return 'Not applicable';
        };
    
        const n1 = parseInt(value1);
        const n2 = parseInt(value2);
    
        return getOperation(n1, n2);
    };
```

**Comment by matteobarone** [comment]
@manuelalonge il primo if. Con il return blocchi l'esecuzione di tutto il codice che viene dopo, e quindi esce dalla funzione

**Comment by matteobarone** [comment]
All Done!
